### PR TITLE
Only mirror language directories, not locale, etc. directories

### PR DESCRIPTION
**Pull request by jpmckinney**
Based on reading http://lftp.yar.ru/lftp-man.html

### CODE REVIEW

**Comment by jpmckinney** [comment]
I see it's uploaded at
http://standard.open-contracting.org/1.1.3-dev/locale/ but not at
http://standard.open-contracting.org/build/locale/

Not sure how that's the case.

**Comment by jpmckinney** [comment]
My build script does however create a build/codelists directory, which is accessible here http://standard.open-contracting.org/build/codelists/

Anyway, perhaps if you have the `mirror` command available (I don't know where to get it from for Homebrew), you can figure out the magic incantation?

**Comment by Bjwebb** [comment]
BTW, `mirror` is a command within lftp's shell, rather than a binary on the local or host machine.

With the updated build script, are there still directories we want to exclude? Specifically aren't CSVs of translated codelists a useful thing to be able to link people to?

**Comment by jpmckinney** [comment]
Aha, I missed the quotes around the subcommand :)

We hadn't published translated codelists CSV files before (except rendered as HTML tables), so I excluded them, not knowing the policy around that, but if we were to publish them, we could put them in build/en/codelists, etc. directories rather than in build/codelists/en.

@timgdavies Any opinion on whether or not to publish translated codelists CSV files?

**Pull request merged**
